---
version: '3.7'

services:
  csapp:
    image: csapp:1.0.0
    container_name: csapp
    read_only: true
    restart: on-failure  
    networks:
      - network1
    environment:
      HOST_NAME: 192.168.1.41
      PORT: 502
      SLAVE_ID: 1
      TIME_BETWEEN_POLLS: 1000
      TIME_BETWEEN_CONTROLS: 1000
      TIMEOUT: 1000
    tmpfs:
      - /temp:uid=5678,gid=5678
networks:
  network1:
    name: edgenet
    external: true
...
